const categoriesEventTypes = {
    IMPORT_CATEGORIES: 'IMPORT_CATEGORIES',
    CREATE_CATEGORIES: 'CREATE_CATEGORIES',
    READ_CATEGORIES: 'READ_CATEGORIES',
    UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
    DELETE_CATEGORIES: 'DELETE_CATEGORIES',
  };
  
  module.exports = categoriesEventTypes;
  